// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUzKjQkFtU9x6FG9xRz8Xy66jetlu80Kc',
    appId: '1:428064096405:web:d434af956c0fa8d9bddb9c',
    messagingSenderId: '428064096405',
    projectId: 'authenticationtask-57752',
    authDomain: 'authenticationtask-57752.firebaseapp.com',
    storageBucket: 'authenticationtask-57752.firebasestorage.app',
    measurementId: 'G-5NSMK1MTMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCloBuPCyoI2X0VFi6lHiCejthy7hdkXhQ',
    appId: '1:428064096405:android:2072cd27ebc86e66bddb9c',
    messagingSenderId: '428064096405',
    projectId: 'authenticationtask-57752',
    storageBucket: 'authenticationtask-57752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO0-GwEArBJkNUrNxV7oqLiP4SqQJIhEs',
    appId: '1:428064096405:ios:436a1ab1f6845e00bddb9c',
    messagingSenderId: '428064096405',
    projectId: 'authenticationtask-57752',
    storageBucket: 'authenticationtask-57752.firebasestorage.app',
    androidClientId: '428064096405-nbpgfpung8ne0htqhfvmop7peis5tnti.apps.googleusercontent.com',
    iosClientId: '428064096405-n4qgg4rgahb3s7po22icc3chn84k2dh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO0-GwEArBJkNUrNxV7oqLiP4SqQJIhEs',
    appId: '1:428064096405:ios:436a1ab1f6845e00bddb9c',
    messagingSenderId: '428064096405',
    projectId: 'authenticationtask-57752',
    storageBucket: 'authenticationtask-57752.firebasestorage.app',
    androidClientId: '428064096405-nbpgfpung8ne0htqhfvmop7peis5tnti.apps.googleusercontent.com',
    iosClientId: '428064096405-n4qgg4rgahb3s7po22icc3chn84k2dh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdj_wcZDGJW4UoXBAIyMzh-3rZklfO9N4',
    appId: '1:428064096405:web:9bf2be046d0241bdbddb9c',
    messagingSenderId: '428064096405',
    projectId: 'authenticationtask-57752',
    authDomain: 'authenticationtask-57752.firebaseapp.com',
    storageBucket: 'authenticationtask-57752.firebasestorage.app',
    measurementId: 'G-YQ57FBMKJC',
  );
}
